---
description: Default pipeline for processing service-proxy logs
processors:
  - rename:
      field: temp.ppbgdi.proxy
      target_field: ppbgdi.app.proxy
      description: Rename temp proxy field
      ignore_missing: true

  - foreach:
      description: Lowercase all http request headers for easier handling
      field: ppbgdi.app.proxy.downstream.http.request.headers
      processor:
        lowercase:
          field: _ingest._key
      ignore_missing: true
  - foreach:
      description: Lowercase all http response headers for easier handling
      field: ppbgdi.app.proxy.downstream.http.response.headers
      processor:
        lowercase:
          field: _ingest._key
      ignore_missing: true

on_failure:
  - set:
      field: event.kind
      value: pipeline_error
  - append:
      field: error.message
      value: >-
        Processor '{{{ _ingest.on_failure_processor_type }}}'
        {{{#_ingest.on_failure_processor_tag}}}with tag '{{{ _ingest.on_failure_processor_tag }}}'
        {{{/_ingest.on_failure_processor_tag}}}failed with message '{{{ _ingest.on_failure_message }}}'
