---
description: Default pipeline for processing python logs
processors:
  - set:
      field: ecs.version
      value: '8.11.0'
      description: Setting the version of the log output of this pipeline
  - set:
      field: event.kind
      value: event
  - set:
      field: event.ingested
      value: '{{_ingest.timestamp}}'
  - append:
      field: tags
      value: no_message
      if: 'ctx?.message == null'
  - append:
      field: tags
      value: empty_message
      if: 'ctx?.message != null && ctx?.message == ""'
  - set:
      field: ppbgdi.app.system
      copy_from: kubernetes.namespace_labels.system # Elastic-Agent
      ignore_empty_value: true
  - set:
      field: ppbgdi.app.system
      copy_from: k8s.namespace.labels.system # OTEL-Collector
      ignore_empty_value: true
  - rename:
      field: message
      target_field: event.original
      ignore_missing: true
      if: 'ctx.event?.original == null'
  - remove:
      field: message
      ignore_missing: true
      if: 'ctx.event?.original != null'
  - grok:
      field: event.original
      patterns:
        - ^%{CHAR:first_char}
      pattern_definitions:
        CHAR: .
  - pipeline:
      description: JSON logs pipeline
      if: ctx.first_char == '{'
      name: '{{ IngestPipeline "common-json" }}'
  - pipeline:
      if: ctx.first_char != '{'
      name: '{{ IngestPipeline "common-raw" }}'
  - pipeline:
      description: Layer object pipeline
      if: ctx?.temp?.ppbgdi?.app?.layer != null
      name: '{{ IngestPipeline "entity-layer" }}'
  - pipeline:
      description: auth-bod object pipeline
      if: ctx.first_char == '{' &&  ctx?.kubernetes?.container?.name == 'auth-bod'
      name: '{{ IngestPipeline "entity-auth-bod" }}'
  - remove:
      field:
        - first_char
  - set:
      field: event.outcome
      value: failure
      if: "ctx?.event?.severity != null && ctx?.event?.severity >= 40"
  - set:
      field: event.outcome
      value: failure
      if: 'ctx?.http?.response?.status_code != null && ctx?.http?.response?.status_code >= 500'
  - set:
      field: event.outcome
      value: success
      if: 'ctx?.event?.outcome == null && ctx?.http?.response?.status_code != null && ctx?.http?.response?.status_code < 500'
  - set:
      field: event.outcome
      value: success
      if: 'ctx?.event?.outcome == null && ctx?.event?.severity != null && ctx?.event?.severity < 40'
  - append:
      field: related.hosts
      value: '{{ source.domain }}'
      allow_duplicates: false
      if: 'ctx?.source?.domain != null'
  - append:
      field: related.hosts
      value: '{{ url.domain }}'
      allow_duplicates: false
      if: 'ctx?.url?.domain != null'
  - append:
      field: related.hosts
      value: '{{ http.request.headers.host }}'
      allow_duplicates: false
      if: 'ctx?.http?.request?.headers?.host != null'
  - append:
      field: related.hosts
      value: '{{ http.request.headers.x-forwarded-host }}'
      allow_duplicates: false
      if: 'ctx?.http?.request?.headers != null && ctx.http.request.headers.containsKey("x-forwarded-host")'
  - set:
      field: service.environment
      copy_from: kubernetes.namespace_labels.env # Elastic-Agent
      ignore_empty_value: true
  - set:
      field: service.environment
      copy_from: k8s.namespace.labels.env # Otel-Collector
      ignore_empty_value: true
  - script:
      lang: painless
      description: This script processor iterates over the whole document to remove fields with null or empty values.
      source: |
        void handleMap(Map map, Map params) {
          for (def x : map.values()) {
            if (x instanceof Map) {
                handleMap(x, params);
            } else if (x instanceof List) {
                handleList(x, params);
            }
          }
          map.values().removeIf(v ->
            (params['remove_null'] == true && v == null) ||
            (params['remove_empty_string'] == true && v == '') ||
            (params['remove_empty_map'] == true && v instanceof Map && v.size() == 0) ||
            (params['remove_empty_list'] == true && v instanceof List && v.size() == 0));
        }
        void handleList(List list, Map params) {
          for (def x : list) {
              if (x instanceof Map) {
                  handleMap(x, params);
              } else if (x instanceof List) {
                  handleList(x, params);
              }
          }
          list.removeIf(v ->
            (params['remove_null_value'] == true && v == null) ||
            (params['remove_empty_string'] == true && v == '') ||
            (params['remove_empty_map'] == true && v instanceof Map && v.size() == 0) ||
            (params['remove_empty_list'] == true && v instanceof List && v.size() == 0));
        }
        handleMap(ctx, params);
      params:
        remove_null: true
        remove_empty_string: false
        remove_empty_map: true
        remove_empty_list: true


on_failure:
  - set:
      field: event.kind
      value: pipeline_error
  - append:
      field: error.message
      value: >-
        Processor '{{{ _ingest.on_failure_processor_type }}}'
        {{{#_ingest.on_failure_processor_tag}}}with tag '{{{ _ingest.on_failure_processor_tag }}}'
        {{{/_ingest.on_failure_processor_tag}}}failed with message '{{{ _ingest.on_failure_message }}}'
